apiVersion: v1
kind: PersistentVolume
metadata:
  name: whiskey-db-pv
spec:
  nfs:
    server: 192.168.8.1
    path: /export/whiskey-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: whiskey-photos-pv
spec:
  nfs:
    server: 192.168.8.1
    path: /export/whiskey-photos
