apiVersion: v1
kind: PersistentVolume
metadata:
  name: whiskey-db-pv
spec:
  nfs:
    server: pinas
    path: /export/whiskey-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: whiskey-photos-pv
spec:
  nfs:
    server: pinas
    path: /export/whiskey-photos
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: whiskey-app-pv
spec:
  nfs:
    server: pinas
    path: /export/whiskey-app

