apiVersion: v1
kind: Service
metadata:
  name: whiskey-service
spec:
  selector:
    app: whiskey-tracker
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080