apiVersion: v1
kind: Service
metadata:
  name: whiskey-service
spec:
  selector:
    app: whiskey-tracker
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080