apiVersion: v1
kind: Pod
metadata:
  name: cleaner
spec:
  restartPolicy: Never
  containers:
    - name: cleaner
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["rm -rf /var/lib/postgresql/data/* && echo Cleaned"]
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-storage
  volumes:
    - name: db-storage
      persistentVolumeClaim:
        claimName: whiskey-db-pvc
