apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - storage.yaml
  - app-service.yaml
  - app-deployment.yaml
  - postgres.yaml
  
secretGenerator:
  - name: whiskey-secrets
    envs:
      - .env

patches:
  - path: patches/nfs-server.yaml
